### ISSUE TITLE
ARM-Executable zu den Releases hinzufügen?

### ISSUE THREAD

**Issue by motz0815** [Niniib/anime4you-dl#10]
Ich weiß nicht, wie einfach das möglich ist, aber es wäre schon ziemlich praktisch, wenn auch für Linux on ARM, wie zum Beispiel einem Raspberry Pi, eine Executable in den Releases beiliegen würde.
Soweit ich weiß kann Rust für Arm Linux kompilieren.

Dem nach, was ich gelesen habe, soll es wohl einfach funktionieren, indem man ein neues target hinzufügt:
`rustup target add armv7-unknown-linux-gnueabihf`

**Comment by Fludixx** [comment]
Ich hab das letzte release bearbeitet und die geleigenheit genutzt ein paar andere binaries auch einzubinden, ich hoffe es funktioniert alles.

**Comment by Niniib** [comment]
Ich hab armv7 getestet und es klappt.
