### ISSUE TITLE
Download Fehler

### ISSUE THREAD

**Issue by existful** [Niniib/anime4you-dl#2]
Hallo, 

Der Downloader geht nicht mehr.
Wollte heute ganz gechillt mit Familie Animes schauen, kann aber jetzt die 2te Seasion nicht mehr runterladen. :-(

Hier die Fehlermeldung:
Waiting 10 seconds before continuing
[*] Fetching Cookies
        [*] Successfully fetched cookies
[*] Fetching vkey
[!] Failed fetching vkey
Waiting 30 seconds before continuing
..... (HTML SALAT) .....

Möglichkeit das zu fixen? 👍 
<3

**Comment by Niniib** [comment]
Ich werde es so schnell wie möglich fixen.
LG

**Comment by Niniib** [comment]
Sollte nun alles wieder funktionieren
