### ISSUE TITLE
Programm geht nicht zu gefailten Folgen zurück

### ISSUE THREAD

**Issue by motz0815** [Niniib/anime4you-dl#7]
Ob das Captcha falsch war, oder kein Hoster verfügbar, eine einmal gefailte Folge wird kein zweites Mal versucht,
meine Erfahrung stammt aus --parallel, aber aufgehängt hat es sich ohne --parallel auch schon.

**Comment by Fludixx** [comment]
Das mit dem Captcha ist ein Fehler, das sollte nicht so sein, aber das eine Folge übersprungen wird, wenn keine Hoster verfügbar sind, ist gewollt, viel beeinflussen kann man da ja nicht.

Ich lasse die Issue offen für Vorschläge, der Fehler beim Captcha wurde im letzten commit behoben.

**Comment by motz0815** [comment]
Nice, danke für die schnelle Reaktion! 👍
