### ISSUE TITLE
Low prio: anime mit sonderzeichen im namen generieren keinen ordner

### ISSUE THREAD

**Issue by motz0815** [Niniib/anime4you-dl#8]
Ist, wie im Titel steht, Low priority, weil es nur einige Anime betrifft, aber:
Wenn ein Anime zB einen : im Titel hat, (zB.: Sword Art Online: Alicization), wird kein Ordner generiert, weil Windows einige Sonderzeichen nicht im Namen von Ordnern akzeptiert.
Diese Sonderzeichen sind \ / : * ? " < > |

**Comment by motz0815** [comment]
Und nein, man kann auch warum auch immer den Ordnernamen mit -o nicht anpassen, wenn ein Anime so ein Sonderzeichen im Namen hat, lädt es einfach gar nicht runter.

**Comment by Fludixx** [comment]
Sollte nun im letzten commit behoben sein, `--out` sollte nun auch wieder gehen.
